# Generated by Django 5.2 on 2025-04-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tahun', models.IntegerField(max_length=5)),
                ('harga_dasar', models.FloatField(max_length=20)),
                ('pinjaman_bank', models.BooleanField()),
                ('dana_pinjaman_bank', models.FloatField(blank=True, max_length=20, null=True)),
                ('suku_bunga', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi', models.CharField(max_length=200)),
                ('biaya', models.FloatField(max_length=20)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobil.mobil')),
            ],
        ),
    ]
