# Generated by Django 5.2 on 2025-04-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobil',
            name='pinjaman_bank',
        ),
    ]
